// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjxEAbN7YHHFyi7XZc7um0aYnGzhFx1i4',
    appId: '1:615034643750:android:bdee601d55a23c38284de7',
    messagingSenderId: '615034643750',
    projectId: 'twittercloneapp-37cd3',
    storageBucket: 'twittercloneapp-37cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfx9j7o5lx0ohfUYU1z8SF8lpvAlRujEc',
    appId: '1:615034643750:ios:808a03dce3cae39f284de7',
    messagingSenderId: '615034643750',
    projectId: 'twittercloneapp-37cd3',
    storageBucket: 'twittercloneapp-37cd3.firebasestorage.app',
    iosBundleId: 'com.example.twitterCloneApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzUN7mvPZvIOR3bzd95mkcBfsEiXJQpKA',
    appId: '1:615034643750:web:f8676cb5e93c0bfa284de7',
    messagingSenderId: '615034643750',
    projectId: 'twittercloneapp-37cd3',
    authDomain: 'twittercloneapp-37cd3.firebaseapp.com',
    storageBucket: 'twittercloneapp-37cd3.firebasestorage.app',
    measurementId: 'G-0KV830KN6D',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzUN7mvPZvIOR3bzd95mkcBfsEiXJQpKA',
    appId: '1:615034643750:web:e0423f8ef107c5be284de7',
    messagingSenderId: '615034643750',
    projectId: 'twittercloneapp-37cd3',
    authDomain: 'twittercloneapp-37cd3.firebaseapp.com',
    storageBucket: 'twittercloneapp-37cd3.firebasestorage.app',
    measurementId: 'G-P0FTR3PVP5',
  );

}